version: "3.9"

services:
  arduino-emu:
    build: arduino-emu
    container_name: arduino-emu
    volumes:
      - .:/workspace:cached
    tty: true
    command: /usr/bin/socat pty,raw,echo=0,link=/dev/ttyACM0 tcp:client:1234
  client:
    build: client
    container_name: client
    volumes:
      - .:/workspace:cached
    tty: true
    command: /usr/bin/socat tcp-l:1234,reuseaddr pty,raw,echo=0,link=/dev/ttyACM0
  server:
    build: server
    container_name: server
    volumes:
      - .:/workspace:cached
    ports:
      - 3000:3000
    tty: true
  broker:
    image: eclipse-mosquitto
    container_name: broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./broker:/mosquitto
    tty: true